# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_remove_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='image',
        ),
    ]
