# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20200307_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='author',
        ),
    ]
